### ISSUE TITLE
0.117.x SonosAlarm causes all speakers go unavailable after restart

### ISSUE THREAD

**Issue by GitHubxtsnl** [AaronDavidSchneider/SonosAlarm#11]
## The problem
All SONOS speakers (entities) (play1, play3, sub, playbar) go unavailable after upgrade to 0.117.x.
Unable to control the SONOS speakers.
![image](https://user-images.githubusercontent.com/43134674/97707835-2c08a200-1ab8-11eb-93d4-d5b15eb96b81.png)

A restart of HA CORE temporarily fixes the issues, for some minutes, after this all entities go unavailable again.

## Environment
Running HomeAssistant CORE 0.117.5 on a Pi4 running HassOS 4.15
last working release was 0.116.4
SonosAlarm: 1.0
Sonos Integration
[SonosAlarm](https://github.com/AaronDavidSchneider/SonosAlarm/issues/new) is apparently causing the issue.

## Problem-relevant `configuration.yaml`
Setup and configuration is done via Configuration \ Integrations, so in my setup no configuration is present for SONOS in configuration.yaml
the SonosAlarm config is done in LovelaceUI

When I remove the SonosAlarm HACS integration the problem is gone and does not come back.

## Traceback/Error logs

Traceback1
```
Logger: homeassistant.components.media_player
Source: components/sonos/media_player.py:699
Integration: Media player (documentation, issues)
First occurred: 1:37:45 PM (1 occurrences)
Last logged: 1:37:45 PM

Error adding entities for domain media_player with platform sonos
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0xa1deb268>, 'Connection to 172.16.210.3 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.16.210.3', port=1400): Max retries exceeded with url: /MediaServer/ContentDirectory/Event (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa1deb268>, 'Connection to 172.16.210.3 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 505, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 550, in async_added_to_hass
    await self.async_seen(self.soco)
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 639, in async_seen
    done = await self.hass.async_add_executor_job(self._attach_player)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 705, in _attach_player
    subscribe(player.contentDirectory, self.update_content)
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 699, in subscribe
    sub = sonos_service.subscribe(auto_renew=True, event_queue=queue)
  File "/usr/local/lib/python3.8/site-packages/pysonos/services.py", line 598, in subscribe
    return subscription.subscribe(
  File "/usr/local/lib/python3.8/site-packages/pysonos/events.py", line 295, in subscribe
    return self._wrap(subscribe, strict, requested_timeout, auto_renew)
  File "/usr/local/lib/python3.8/site-packages/pysonos/events.py", line 433, in _wrap
    method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pysonos/events_base.py", line 477, in subscribe
    return self._request(
  File "/usr/local/lib/python3.8/site-packages/pysonos/events.py", line 389, in _request
    response = requests.request(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='172.16.210.3', port=1400): Max retries exceeded with url: /MediaServer/ContentDirectory/Event (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xa1deb268>, 'Connection to 172.16.210.3 timed out. (connect timeout=3)'))
```

Traceback2
```
Logger: homeassistant.components.media_player
Source: components/sonos/media_player.py:699
Integration: Media player (documentation, issues)
First occurred: 1:38:09 PM (1 occurrences)
Last logged: 1:38:09 PM

Error adding entities for domain media_player with platform sonos
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='172.16.210.6', port=1400): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 505, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 550, in async_added_to_hass
    await self.async_seen(self.soco)
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 639, in async_seen
    done = await self.hass.async_add_executor_job(self._attach_player)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 702, in _attach_player
    subscribe(player.avTransport, self.update_media)
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 699, in subscribe
    sub = sonos_service.subscribe(auto_renew=True, event_queue=queue)
  File "/usr/local/lib/python3.8/site-packages/pysonos/services.py", line 598, in subscribe
    return subscription.subscribe(
  File "/usr/local/lib/python3.8/site-packages/pysonos/events.py", line 295, in subscribe
    return self._wrap(subscribe, strict, requested_timeout, auto_renew)
  File "/usr/local/lib/python3.8/site-packages/pysonos/events.py", line 433, in _wrap
    method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pysonos/events_base.py", line 477, in subscribe
    return self._request(
  File "/usr/local/lib/python3.8/site-packages/pysonos/events.py", line 389, in _request
    response = requests.request(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='172.16.210.6', port=1400): Read timed out. (read timeout=3)
```

I have not tested if this issue is there when adding the SONOS speakers manually to the configuration.yaml.
Also good to know all my SONOS speakers get a fixed IP address (reservations) from my DHCP Server and are connected to the same wireless network. All the speakers are pingable.

EDIT: I've removed the Configuration \ Integration \ SONOS and restarted HA with manual setup of SONOS devices in configuration.yaml and the same problem occurs:
here is my manual current config:
```
sonos:
  media_player:
    interface_addr: !secret ha_ip
    advertise_addr: !secret ha_ip
    hosts:
        - 172.16.210.1 # SONOS-WK-PLAY3-R
        - 172.16.210.2 # SONOS-WK-PLAY3-L
        - 172.16.210.3 # SONOS-WK-AMP
        - 172.16.210.4 # SONOS-OFFICE-AMP
        - 172.16.210.5 # SONOS-SK1-PLAY1
        - 172.16.210.6 # SONOS-WK-PLAYBAR
        - 172.16.210.7 # SONOS-WK-SUB
        - 172.16.210.8 # SONOS-KEUKEN-PLAY3
        - 172.16.210.9 # SONOS-ZO-PLAY1
        - 172.16.210.10 # SONOS-SK4-PLAY1
        - 172.16.210.11 # SONOS-SK5-PLAY1
```

**Comment by AaronDavidSchneider** [comment]
Hi,

thanks for reporting!! 

The traceback is not at all related to SonosAlarm...  I do not understand why the error disappears when removing SonosAlarm.

Could you do me a favor and remove the sonos integration and instead only add SonosAlarm to test wether it works this way too?

It could be that there are too many requests to the sonos api. In this case we should lower the `SCAN_INTERVAL`.

Let me know what you find.

I think we found a similar issue in fritzbox tools: https://github.com/mammuth/ha-fritzbox-tools/issues/130

**Comment by GitHubxtsnl** [comment]
Hello, thank you for the quick response. I will do some more testing tonight or tomorrow. And I will report back here.

**Comment by AaronDavidSchneider** [comment]
Any progress?

**Comment by GitHubxtsnl** [comment]
I've upgraded HA to 0.118.3 and re-installed the Sonos Alarm HACS integration and the log now remains empty, no errors on the Sonos Alarm integration or Sonos integration anymore.
This issue can be marked as closed as far as I'm concerned.
